export const ActionTypes = {
    SET_GENERIC: "SET_GENERIC",
    SET_MODEL: "SET_MODEL",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT"
}